In [55]:
import pandas as pd

In [68]:
flow_block_df = pd.read_pickle("output/flow-block.pkl")

In [69]:
describe_all_episode = []
for i in flow_block_df['block-id'].unique():
    description = {}
    df_descriptions = flow_block_df[flow_block_df['block-id'] == i].describe()
    description['mean_interval-timestamp'] = df_descriptions['interval-timestamp']['mean']
    description['std_interval-timestamp'] = df_descriptions['interval-timestamp']['std']
    description['interval-distribution'] = df_descriptions['reception-timestamp']['max'] - df_descriptions['transmission-timestamp']['min']
    description['block_size'] = df_descriptions['block-size']['mean']
    
    describe_all_episode.append(description)

df_describe = pd.DataFrame(describe_all_episode)

In [70]:
df_describe

,mean_interval-timestamp,std_interval-timestamp,interval-distribution,block_size
0,1120.178161,458.742548,50904.0,535000.0
1,1068.086207,449.847744,51553.0,535000.0
2,1196.534483,590.976547,62317.0,535000.0
3,1013.816092,392.473644,47923.0,535000.0
4,1114.390805,382.378149,45950.0,535000.0
...,...,...,...,...
95,1098.206897,341.102874,51861.0,535000.0
96,1078.017241,447.404105,44125.0,535000.0
97,1078.356322,511.790927,50628.0,535000.0
98,1192.172414,581.076144,51334.0,535000.0
99,1049.390805,354.621539,46288.0,535000.0

In [94]:
df_describe.describe()

,mean_interval-timestamp,std_interval-timestamp,interval-distribution,block_size
count,100.000000,100.000000,100.000000,100.0
mean,1092.165460,454.621882,50000.460000,535000.0
std,49.356230,73.955364,4922.308595,0.0
min,977.942529,340.803123,36442.000000,535000.0
25%,1060.655172,392.183824,47080.250000,535000.0
50%,1091.770115,450.029591,50750.000000,535000.0
75%,1120.229885,495.758566,52790.500000,535000.0
max,1203.074713,613.581716,62512.000000,535000.0

In [99]:
import json

# read file
with open('/home/ichwan/Documents/Blockchain/simblock/simulator/src/dist/output/output.json', 'r') as myfile:
    data=json.loads(myfile.read())

In [100]:
df_describe2.describe()

,mean_interval-timestamp,std_interval-timestamp,interval-distribution,block_size
count,105.000000,105.000000,105.000000,105.0
mean,745.282523,116.729758,17127.095238,535000.0
std,170.491040,50.202996,5737.868586,0.0
min,609.994253,77.210176,10164.000000,535000.0
25%,611.537572,85.118369,12378.000000,535000.0
50%,617.454023,95.016071,15340.000000,535000.0
75%,968.597701,127.836617,20486.000000,535000.0
max,1023.224138,307.043874,32971.000000,535000.0

In [101]:
def makePandas(listDict, kind):
    data = [raw['content'] for raw in listDict if raw['kind'] == kind]
    df = pd.DataFrame(data) 
    return df

In [102]:
flow_block_df2 = makePandas(data, "flow-block")

In [103]:
describe_all_episode2 = []
for i in flow_block_df2['block-id'].unique():
    description = {}
    df_descriptions2 = flow_block_df2[flow_block_df2['block-id'] == i].describe()
    description['mean_interval-timestamp'] = df_descriptions2['interval-timestamp']['mean']
    description['std_interval-timestamp'] = df_descriptions2['interval-timestamp']['std']
    description['interval-distribution'] = df_descriptions2['reception-timestamp']['max'] - df_descriptions2['transmission-timestamp']['min']
    description['block_size'] = 535000
    
    describe_all_episode2.append(description)

df_describe2 = pd.DataFrame(describe_all_episode2)

In [104]:
df_descriptions2 = flow_block_df2[flow_block_df2['block-id'] == i].describe()

In [106]:
df_describe2

,mean_interval-timestamp,std_interval-timestamp,interval-distribution,block_size
0,1059.281609,142.368187,23736.0,535000
1,617.011494,97.020824,15144.0,535000
2,988.488506,122.275333,22327.0,535000
3,612.701149,91.034214,13777.0,535000
4,612.821839,88.141029,13067.0,535000
...,...,...,...,...
102,1008.120690,87.320633,19592.0,535000
103,999.603448,103.268370,22499.0,535000
104,1007.413793,91.434307,22235.0,535000
105,615.563218,94.433045,11806.0,535000
106,610.862069,84.855562,15991.0,535000

In [86]:
flow_block_df[flow_block_df['block-id'] == 6]

,interval-timestamp,transmission-timestamp,reception-timestamp,begin-node-id,end-node-id,block-id,block-size
870,844,3000002,3000846,767,764,6,535000
871,841,3000846,3001687,764,762,6,535000
872,860,3001687,3002547,762,763,6,535000
873,1028,3002547,3003575,763,16,6,535000
874,970,3003575,3004545,16,8,6,535000
...,...,...,...,...,...,...,...
1039,843,3000002,3000845,767,766,6,535000
1040,841,3000002,3000843,767,765,6,535000
1041,840,3000002,3000842,767,761,6,535000
1042,1103,3000002,3001105,767,630,6,535000
1043,987,3000002,3000989,767,726,6,535000

In [85]:
flow_block_df2[flow_block_df2['block-id'] == 6]

,interval-timestamp,transmission-timestamp,reception-timestamp,begin-node-id,end-node-id,block-id
1044,537,830358,830895,104,19,6
1045,551,830895,831446,104,114,6
1046,539,830933,831472,19,86,6
1047,537,831472,832009,19,120,6
1048,563,831446,832009,104,175,6
...,...,...,...,...,...,...
1213,646,842325,842971,114,141,6
1214,883,842169,843052,175,1,6
1215,648,842971,843619,114,174,6
1216,771,843619,844390,114,90,6
1217,769,844390,845159,114,38,6

In [114]:
df_describe

,mean_interval-timestamp,std_interval-timestamp,interval-distribution,block_size,mean_interval
0,1120.178161,458.742548,50904.0,535000.0,1059.281609
1,1068.086207,449.847744,51553.0,535000.0,617.011494
2,1196.534483,590.976547,62317.0,535000.0,988.488506
3,1013.816092,392.473644,47923.0,535000.0,612.701149
4,1114.390805,382.378149,45950.0,535000.0,612.821839
...,...,...,...,...,...
95,1098.206897,341.102874,51861.0,535000.0,611.844828
96,1078.017241,447.404105,44125.0,535000.0,991.505747
97,1078.356322,511.790927,50628.0,535000.0,1082.252874
98,1192.172414,581.076144,51334.0,535000.0,995.885057
99,1049.390805,354.621539,46288.0,535000.0,992.316092

In [115]:
df_describe2

,mean_interval-timestamp,std_interval-timestamp,interval-distribution,block_size
0,1059.281609,142.368187,23736.0,535000
1,617.011494,97.020824,15144.0,535000
2,988.488506,122.275333,22327.0,535000
3,612.701149,91.034214,13777.0,535000
4,612.821839,88.141029,13067.0,535000
...,...,...,...,...
102,1008.120690,87.320633,19592.0,535000
103,999.603448,103.268370,22499.0,535000
104,1007.413793,91.434307,22235.0,535000
105,615.563218,94.433045,11806.0,535000
106,610.862069,84.855562,15991.0,535000

In [116]:
df_describe['interval-distribution2'] = df_describe2['interval-distribution'].values[:100]

In [117]:
df_describe.to_csv('File Name.csv')

In [29]:
import grequests

urls = [
('http://httpbin.org/ip', ('185.95.184.4','8080'))
, ('http://httpbin.org/ip', ('148.251.200.197','1080'))
, ('http://httpbin.org/ip', ('193.117.138.126','40910'))
, ('http://httpbin.org/ip', ('84.22.59.202','8080'))
, ('http://httpbin.org/ip', ('186.159.3.49','41589'))
, ('http://httpbin.org/ip', ('85.10.219.98','1080'))
, ('http://httpbin.org/ip', ('93.78.238.94','41258'))
, ('http://httpbin.org/ip', ('94.130.125.222','1080'))
, ('http://httpbin.org/ip', ('46.235.53.26','3128'))
, ('http://httpbin.org/ip', ('190.186.89.150','35759'))
]

rs = (grequests.get(u[0],
                        proxies={ 'http': 'http://148.251.200.197:1080' },
                        headers={'x-my-proxy' : '148.251.200.197 1080' },
                        timeout=20) for u in urls)
for i in grequests.map(rs):
    if i:
        print(i.content)

b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'

In [30]:

rs = (grequests.get(u[0],
                        proxies={ 'http': 'http://148.251.200.197:1080' },
                        headers={'x-my-proxy' : '148.251.200.197 1080' },
                        timeout=20) for u in urls)
for i in grequests.map(rs):
    if i:
        print(i.content)

b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'
b'{\n  "origin": "148.251.200.197"\n}\n'

In [1]:
#!/usr/bin/env python
import psutil
# gives a single float value
psutil.cpu_percent()
# gives an object with many fields
psutil.virtual_memory()
# you can convert that object to a dictionary 
dict(psutil.virtual_memory()._asdict())

{'total': 16733093888,
 'available': 4197494784,
 'percent': 74.9,
 'used': 10134446080,
 'free': 2458583040,
 'active': 10722324480,
 'inactive': 2730082304,
 'buffers': 843411456,
 'cached': 3296653312,
 'shared': 2080755712,
 'slab': 406827008}

In [12]:
psutil.virtual_memory()

svmem(total=16733093888, available=4216717312, percent=74.8, used=10170142720, free=2461532160, active=10764484608, inactive=2684805120, buffers=844996608, cached=3256422400, shared=2026901504, slab=406982656)

In [5]:
pid_name()

[{'name': 'systemd', 'pid': 1},
 {'name': 'kthreadd', 'pid': 2},
 {'name': 'kworker/0:0H', 'pid': 4},
 {'name': 'mm_percpu_wq', 'pid': 6},
 {'name': 'ksoftirqd/0', 'pid': 7},
 {'name': 'rcu_sched', 'pid': 8},
 {'name': 'rcu_bh', 'pid': 9},
 {'name': 'migration/0', 'pid': 10},
 {'name': 'watchdog/0', 'pid': 11},
 {'name': 'cpuhp/0', 'pid': 12},
 {'name': 'cpuhp/1', 'pid': 13},
 {'name': 'watchdog/1', 'pid': 14},
 {'name': 'migration/1', 'pid': 15},
 {'name': 'ksoftirqd/1', 'pid': 16},
 {'name': 'kworker/1:0H', 'pid': 18},
 {'name': 'cpuhp/2', 'pid': 19},
 {'name': 'watchdog/2', 'pid': 20},
 {'name': 'migration/2', 'pid': 21},
 {'name': 'ksoftirqd/2', 'pid': 22},
 {'name': 'kworker/2:0H', 'pid': 24},
 {'name': 'cpuhp/3', 'pid': 25},
 {'name': 'watchdog/3', 'pid': 26},
 {'name': 'migration/3', 'pid': 27},
 {'name': 'ksoftirqd/3', 'pid': 28},
 {'name': 'kworker/3:0H', 'pid': 30},
 {'name': 'cpuhp/4', 'pid': 31},
 {'name': 'watchdog/4', 'pid': 32},
 {'name': 'migration/4', 'pid': 33},
 {'name': 'ksoftirqd/4', 'pid': 34},
 {'name': 'kworker/4:0H', 'pid': 36},
 {'name': 'cpuhp/5', 'pid': 37},
 {'name': 'watchdog/5', 'pid': 38},
 {'name': 'migration/5', 'pid': 39},
 {'name': 'ksoftirqd/5', 'pid': 40},
 {'name': 'kworker/5:0H', 'pid': 42},
 {'name': 'cpuhp/6', 'pid': 43},
 {'name': 'watchdog/6', 'pid': 44},
 {'name': 'migration/6', 'pid': 45},
 {'name': 'ksoftirqd/6', 'pid': 46},
 {'name': 'kworker/6:0H', 'pid': 48},
 {'name': 'cpuhp/7', 'pid': 49},
 {'name': 'watchdog/7', 'pid': 50},
 {'name': 'migration/7', 'pid': 51},
 {'name': 'ksoftirqd/7', 'pid': 52},
 {'name': 'kworker/7:0H', 'pid': 54},
 {'name': 'kdevtmpfs', 'pid': 55},
 {'name': 'netns', 'pid': 56},
 {'name': 'rcu_tasks_kthre', 'pid': 57},
 {'name': 'kauditd', 'pid': 58},
 {'name': 'khungtaskd', 'pid': 62},
 {'name': 'oom_reaper', 'pid': 63},
 {'name': 'writeback', 'pid': 64},
 {'name': 'kcompactd0', 'pid': 65},
 {'name': 'ksmd', 'pid': 66},
 {'name': 'khugepaged', 'pid': 67},
 {'name': 'crypto', 'pid': 68},
 {'name': 'kintegrityd', 'pid': 69},
 {'name': 'kblockd', 'pid': 70},
 {'name': 'ata_sff', 'pid': 76},
 {'name': 'md', 'pid': 77},
 {'name': 'edac-poller', 'pid': 78},
 {'name': 'devfreq_wq', 'pid': 79},
 {'name': 'watchdogd', 'pid': 80},
 {'name': 'kswapd0', 'pid': 83},
 {'name': 'ecryptfs-kthrea', 'pid': 85},
 {'name': 'kthrotld', 'pid': 127},
 {'name': 'acpi_thermal_pm', 'pid': 128},
 {'name': 'ipv6_addrconf', 'pid': 134},
 {'name': 'kstrp', 'pid': 143},
 {'name': 'charger_manager', 'pid': 160},
 {'name': 'scsi_eh_0', 'pid': 220},
 {'name': 'scsi_tmf_0', 'pid': 221},
 {'name': 'scsi_eh_1', 'pid': 222},
 {'name': 'scsi_tmf_1', 'pid': 223},
 {'name': 'scsi_eh_2', 'pid': 224},
 {'name': 'scsi_tmf_2', 'pid': 225},
 {'name': 'scsi_eh_3', 'pid': 226},
 {'name': 'scsi_tmf_3', 'pid': 227},
 {'name': 'kworker/7:1H', 'pid': 232},
 {'name': 'kworker/2:1H', 'pid': 265},
 {'name': 'kworker/1:1H', 'pid': 266},
 {'name': 'jbd2/sda6-8', 'pid': 268},
 {'name': 'ext4-rsv-conver', 'pid': 269},
 {'name': 'systemd-journald', 'pid': 319},
 {'name': 'systemd-udevd', 'pid': 334},
 {'name': 'lvmetad', 'pid': 337},
 {'name': 'kworker/0:1H', 'pid': 339},
 {'name': 'kworker/4:1H', 'pid': 340},
 {'name': 'kworker/3:1H', 'pid': 346},
 {'name': 'loop0', 'pid': 376},
 {'name': 'loop1', 'pid': 389},
 {'name': 'loop2', 'pid': 391},
 {'name': 'loop3', 'pid': 392},
 {'name': 'loop4', 'pid': 393},
 {'name': 'loop5', 'pid': 394},
 {'name': 'loop6', 'pid': 395},
 {'name': 'loop7', 'pid': 396},
 {'name': 'loop8', 'pid': 397},
 {'name': 'loop9', 'pid': 398},
 {'name': 'loop10', 'pid': 399},
 {'name': 'loop11', 'pid': 400},
 {'name': 'loop12', 'pid': 401},
 {'name': 'loop13', 'pid': 403},
 {'name': 'loop14', 'pid': 409},
 {'name': 'loop15', 'pid': 416},
 {'name': 'loop16', 'pid': 417},
 {'name': 'loop17', 'pid': 418},
 {'name': 'loop18', 'pid': 419},
 {'name': 'loop19', 'pid': 420},
 {'name': 'kworker/5:1H', 'pid': 421},
 {'name': 'loop20', 'pid': 422},
 {'name': 'loop21', 'pid': 423},
 {'name': 'loop22', 'pid': 424},
 {'name': 'loop23', 'pid': 425},
 {'name': 'loop24', 'pid': 426},
 {'name': 'i915/signal:0', 'pid': 448},
 {'name': 'i915/signal:1', 'pid': 449},
 {'name': 'i915/signal:2', 'pid': 450},
 {'name': 'i915/signal:4', 'pid': 451},
 {'name': 'kmemstick', 'pid': 471},
 {'name': 'kworker/6:1H', 'pid': 473},
 {'name': 'cfg80211', 'pid': 477},
 {'name': 'kworker/u17:2', 'pid': 480},
 {'name': 'irq/129-iwlwifi', 'pid': 481},
 {'name': 'systemd-resolved', 'pid': 932},
 {'name': 'systemd-timesyncd', 'pid': 934},
 {'name': 'chrome', 'pid': 1000},
 {'name': 'udisksd', 'pid': 1112},
 {'name': 'accounts-daemon', 'pid': 1115},
 {'name': 'avahi-daemon', 'pid': 1120},
 {'name': 'bluetoothd', 'pid': 1121},
 {'name': 'avahi-daemon', 'pid': 1147},
 {'name': 'cron', 'pid': 1153},
 {'name': 'systemd-logind', 'pid': 1156},
 {'name': 'dbus-daemon', 'pid': 1174},
 {'name': 'wpa_supplicant', 'pid': 1208},
 {'name': 'acpid', 'pid': 1240},
 {'name': 'ModemManager', 'pid': 1244},
 {'name': 'snapd', 'pid': 1252},
 {'name': 'networkd-dispat', 'pid': 1253},
 {'name': 'rsyslogd', 'pid': 1255},
 {'name': 'irqbalance', 'pid': 1256},
 {'name': 'chrome', 'pid': 1284},
 {'name': 'thermald', 'pid': 1288},
 {'name': 'NetworkManager', 'pid': 1293},
 {'name': 'chrome', 'pid': 1312},
 {'name': 'polkitd', 'pid': 1389},
 {'name': 'libvirtd', 'pid': 1579},
 {'name': 'unattended-upgr', 'pid': 1584},
 {'name': 'winbindd', 'pid': 1588},
 {'name': 'containerd', 'pid': 1601},
 {'name': 'gnome-terminal-server', 'pid': 1653},
 {'name': 'gdm3', 'pid': 1658},
 {'name': 'bash', 'pid': 1664},
 {'name': 'gdm-session-wor', 'pid': 1692},
 {'name': 'winbindd', 'pid': 1703},
 {'name': 'gvfsd-http', 'pid': 1809},
 {'name': 'systemd', 'pid': 1811},
 {'name': '(sd-pam)', 'pid': 1823},
 {'name': 'gdm-wayland-session', 'pid': 1863},
 {'name': 'dbus-daemon', 'pid': 1865},
 {'name': 'gnome-session-binary', 'pid': 1868},
 {'name': 'gnome-shell', 'pid': 1894},
 {'name': 'upowerd', 'pid': 1924},
 {'name': 'Xwayland', 'pid': 2029},
 {'name': 'dnsmasq', 'pid': 2097},
 {'name': 'dnsmasq', 'pid': 2098},
 {'name': 'at-spi-bus-launcher', 'pid': 2139},
 {'name': 'dbus-daemon', 'pid': 2144},
 {'name': 'at-spi2-registryd', 'pid': 2146},
 {'name': 'pulseaudio', 'pid': 2235},
 {'name': 'rtkit-daemon', 'pid': 2247},
 {'name': 'ibus-daemon', 'pid': 2348},
 {'name': 'ibus-dconf', 'pid': 2351},
 {'name': 'ibus-x11', 'pid': 2353},
 {'name': 'ibus-portal', 'pid': 2356},
 {'name': 'xdg-permission-store', 'pid': 2364},
 {'name': 'boltd', 'pid': 2389},
 {'name': 'packagekitd', 'pid': 2397},
 {'name': 'gsd-xsettings', 'pid': 2407},
 {'name': 'gsd-a11y-settings', 'pid': 2409},
 {'name': 'gsd-clipboard', 'pid': 2413},
 {'name': 'gsd-color', 'pid': 2426},
 {'name': 'gsd-datetime', 'pid': 2427},
 {'name': 'gsd-housekeeping', 'pid': 2428},
 {'name': 'gsd-keyboard', 'pid': 2429},
 {'name': 'gsd-media-keys', 'pid': 2430},
 {'name': 'gsd-mouse', 'pid': 2433},
 {'name': 'gsd-power', 'pid': 2436},
 {'name': 'gsd-print-notifications', 'pid': 2443},
 {'name': 'gsd-rfkill', 'pid': 2445},
 {'name': 'gsd-screensaver-proxy', 'pid': 2446},
 {'name': 'gsd-sharing', 'pid': 2448},
 {'name': 'gsd-smartcard', 'pid': 2452},
 {'name': 'gsd-sound', 'pid': 2456},
 {'name': 'gsd-wacom', 'pid': 2459},
 {'name': 'ibus-engine-simple', 'pid': 2474},
 {'name': 'colord', 'pid': 2537},
 {'name': 'whoopsie', 'pid': 2765},
 {'name': 'kerneloops', 'pid': 2787},
 {'name': 'kerneloops', 'pid': 2800},
 {'name': 'teamviewerd', 'pid': 2806},
 {'name': 'chrome', 'pid': 2977},
 {'name': 'gdm-session-wor', 'pid': 3014},
 {'name': 'systemd', 'pid': 3028},
 {'name': '(sd-pam)', 'pid': 3029},
 {'name': 'gnome-keyring-daemon', 'pid': 3042},
 {'name': 'gdm-x-session', 'pid': 3046},
 {'name': 'Xorg', 'pid': 3048},
 {'name': 'dbus-daemon', 'pid': 3054},
 {'name': 'gnome-session-binary', 'pid': 3057},
 {'name': 'ssh-agent', 'pid': 3152},
 {'name': 'at-spi-bus-launcher', 'pid': 3155},
 {'name': 'dbus-daemon', 'pid': 3160},
 {'name': 'at-spi2-registryd', 'pid': 3162},
 {'name': 'gnome-shell', 'pid': 3180},
 {'name': 'gvfsd', 'pid': 3187},
 {'name': 'gvfsd-fuse', 'pid': 3192},
 {'name': 'pulseaudio', 'pid': 3204},
 {'name': 'krfcommd', 'pid': 3221},
 {'name': 'ibus-daemon', 'pid': 3223},
 {'name': 'ibus-dconf', 'pid': 3227},
 {'name': 'ibus-x11', 'pid': 3229},
 {'name': 'ibus-portal', 'pid': 3231},
 {'name': 'xdg-permission-store', 'pid': 3240},
 {'name': 'gnome-shell-calendar-server', 'pid': 3247},
 {'name': 'evolution-source-registry', 'pid': 3251},
 {'name': 'goa-daemon', 'pid': 3260},
 {'name': 'gvfs-udisks2-volume-monitor', 'pid': 3278},
 {'name': 'goa-identity-service', 'pid': 3288},
 {'name': 'gvfs-afc-volume-monitor', 'pid': 3293},
 {'name': 'gvfs-goa-volume-monitor', 'pid': 3298},
 {'name': 'gvfs-gphoto2-volume-monitor', 'pid': 3302},
 {'name': 'gvfs-mtp-volume-monitor', 'pid': 3306},
 {'name': 'gsd-power', 'pid': 3313},
 {'name': 'gsd-print-notifications', 'pid': 3314},
 {'name': 'gsd-rfkill', 'pid': 3315},
 {'name': 'gsd-screensaver-proxy', 'pid': 3316},
 {'name': 'gsd-sharing', 'pid': 3319},
 {'name': 'gsd-smartcard', 'pid': 3325},
 {'name': 'gsd-sound', 'pid': 3327},
 {'name': 'gsd-xsettings', 'pid': 3332},
 {'name': 'gsd-wacom', 'pid': 3341},
 {'name': 'gsd-clipboard', 'pid': 3344},
 {'name': 'gsd-a11y-settings', 'pid': 3345},
 {'name': 'gsd-datetime', 'pid': 3349},
 {'name': 'gsd-color', 'pid': 3353},
 {'name': 'gsd-keyboard', 'pid': 3355},
 {'name': 'gsd-housekeeping', 'pid': 3358},
 {'name': 'gsd-mouse', 'pid': 3359},
 {'name': 'gsd-media-keys', 'pid': 3363},
 {'name': 'gsd-printer', 'pid': 3396},
 {'name': 'gsd-disk-utility-notify', 'pid': 3410},
 {'name': 'kdeconnectd', 'pid': 3420},
 {'name': 'nautilus-desktop', 'pid': 3421},
 {'name': 'gvfsd-trash', 'pid': 3454},
 {'name': 'chrome', 'pid': 3481},
 {'name': 'evolution-calendar-factory', 'pid': 3490},
 {'name': 'dconf-service', 'pid': 3494},
 {'name': 'ibus-engine-simple', 'pid': 3499},
 {'name': 'evolution-calendar-factory-subprocess', 'pid': 3512},
 {'name': 'evolution-addressbook-factory', 'pid': 3525},
 {'name': 'evolution-addressbook-factory-subprocess', 'pid': 3535},
 {'name': 'gvfsd-metadata', 'pid': 3548},
 {'name': 'update-notifier', 'pid': 3757},
 {'name': 'gnome-software', 'pid': 3760},
 {'name': 'fwupd', 'pid': 3805},
 {'name': 'code', 'pid': 4028},
 {'name': 'bash', 'pid': 4054},
 {'name': 'code', 'pid': 4063},
 {'name': 'code', 'pid': 4088},
 {'name': 'cupsd', 'pid': 4321},
 {'name': 'cups-browsed', 'pid': 4322},
 {'name': 'dbus', 'pid': 4341},
 {'name': 'nautilus', 'pid': 4406},
 {'name': 'bash', 'pid': 4451},
 {'name': 'chrome', 'pid': 4784},
 {'name': 'chrome', 'pid': 4807},
 {'name': 'kworker/4:1', 'pid': 4943},
 {'name': 'chrome', 'pid': 5418},
 {'name': 'chrome', 'pid': 5523},
 {'name': 'chrome', 'pid': 5579},
 {'name': 'chrome', 'pid': 5616},
 {'name': 'chrome', 'pid': 5713},
 {'name': 'chrome', 'pid': 5731},
 {'name': 'chrome', 'pid': 5760},
 {'name': 'chrome', 'pid': 5791},
 {'name': 'chrome', 'pid': 5797},
 {'name': 'chrome', 'pid': 5798},
 {'name': 'chrome', 'pid': 5837},
 {'name': 'chrome', 'pid': 5844},
 {'name': 'chrome', 'pid': 5895},
 {'name': 'chrome', 'pid': 6000},
 {'name': 'chrome', 'pid': 6038},
 {'name': 'chrome', 'pid': 6051},
 {'name': 'chrome', 'pid': 6113},
 {'name': 'chrome', 'pid': 6131},
 {'name': 'chrome', 'pid': 6147},
 {'name': 'chrome', 'pid': 6334},
 {'name': 'chrome', 'pid': 6458},
 {'name': 'chrome', 'pid': 6501},
 {'name': 'chrome', 'pid': 6527},
 {'name': 'chrome', 'pid': 6734},
 {'name': 'chrome', 'pid': 6783},
 {'name': 'chrome', 'pid': 6895},
 {'name': 'chrome', 'pid': 7043},
 {'name': 'chrome', 'pid': 7302},
 {'name': 'chrome', 'pid': 7341},
 {'name': 'cat', 'pid': 7347},
 {'name': 'cat', 'pid': 7348},
 {'name': 'chrome', 'pid': 7351},
 {'name': 'nacl_helper', 'pid': 7352},
 {'name': 'chrome', 'pid': 7355},
 {'name': 'chrome', 'pid': 7375},
 {'name': 'chrome', 'pid': 7380},
 {'name': 'chrome', 'pid': 7461},
 {'name': 'chrome', 'pid': 7484},
 {'name': 'chrome', 'pid': 7491},
 {'name': 'chrome', 'pid': 7497},
 {'name': 'chrome', 'pid': 7637},
 {'name': 'chrome', 'pid': 7748},
 {'name': 'chrome', 'pid': 7875},
 {'name': 'chrome', 'pid': 8398},
 {'name': 'chrome', 'pid': 8404},
 {'name': 'chrome', 'pid': 8422},
 {'name': 'chrome', 'pid': 8457},
 {'name': 'chrome', 'pid': 8537},
 {'name': 'chrome', 'pid': 8592},
 {'name': 'gvfsd-network', 'pid': 9722},
 {'name': 'gvfsd-dnssd', 'pid': 9762},
 {'name': 'chrome', 'pid': 9925},
 {'name': 'bash', 'pid': 10742},
 {'name': 'bash', 'pid': 10792},
 {'name': 'kworker/1:0', 'pid': 11275},
 {'name': 'kworker/3:2', 'pid': 11335},
 {'name': 'chrome', 'pid': 11545},
 {'name': 'chrome', 'pid': 11583},
 {'name': 'irq/126-mei_me', 'pid': 11870},
 {'name': 'kworker/u17:0', 'pid': 11875},
 {'name': 'kworker/7:0', 'pid': 12796},
 {'name': 'chrome', 'pid': 13134},
 {'name': 'chrome', 'pid': 13249},
 {'name': 'kworker/2:0', 'pid': 13318},
 {'name': 'chrome', 'pid': 13394},
 {'name': 'bash', 'pid': 13545},
 {'name': 'chrome', 'pid': 13636},
 {'name': 'code', 'pid': 13676},
 {'name': 'code', 'pid': 13680},
 {'name': 'code', 'pid': 13717},
 {'name': 'code', 'pid': 13741},
 {'name': 'code', 'pid': 13799},
 {'name': 'code', 'pid': 13820},
 {'name': 'code', 'pid': 13869},
 {'name': 'kworker/5:1', 'pid': 14100},
 {'name': 'code', 'pid': 14134},
 {'name': 'kworker/6:0', 'pid': 14209},
 {'name': 'kworker/u16:1', 'pid': 14231},
 {'name': 'chrome', 'pid': 14581},
 {'name': 'chrome', 'pid': 14846},
 {'name': 'kworker/0:3', 'pid': 14859},
 {'name': 'chrome', 'pid': 14913},
 {'name': 'bash', 'pid': 14996},
 {'name': 'dockerd', 'pid': 15171},
 {'name': 'docker-proxy', 'pid': 16119},
 {'name': 'containerd-shim', 'pid': 16127},
 {'name': 'sh', 'pid': 16155},
 {'name': 'bash', 'pid': 16226},
 {'name': 'su', 'pid': 16382},
 {'name': 'postgres', 'pid': 16383},
 {'name': 'postgres', 'pid': 16387},
 {'name': 'postgres', 'pid': 16388},
 {'name': 'postgres', 'pid': 16389},
 {'name': 'postgres', 'pid': 16390},
 {'name': 'postgres', 'pid': 16391},
 {'name': 'sudo', 'pid': 16593},
 {'name': 'docker', 'pid': 16594},
 {'name': 'containerd-shim', 'pid': 16681},
 {'name': 'sh', 'pid': 16712},
 {'name': 'kworker/7:2', 'pid': 17157},
 {'name': 'kworker/0:0', 'pid': 17222},
 {'name': 'chrome', 'pid': 17278},
 {'name': 'chrome', 'pid': 17369},
 {'name': 'kworker/u16:2', 'pid': 17398},
 {'name': 'dhclient', 'pid': 17436},
 {'name': 'chrome', 'pid': 17736},
 {'name': 'chrome', 'pid': 17846},
 {'name': 'kworker/2:2', 'pid': 17888},
 {'name': 'kworker/4:2', 'pid': 17958},
 {'name': 'chrome', 'pid': 17961},
 {'name': 'apt-get', 'pid': 18077},
 {'name': 'http', 'pid': 18082},
 {'name': 'http', 'pid': 18083},
 {'name': 'kworker/6:1', 'pid': 18103},
 {'name': 'kworker/u16:3', 'pid': 18104},
 {'name': 'kworker/1:1', 'pid': 18144},
 {'name': 'chrome', 'pid': 18248},
 {'name': 'kworker/3:0', 'pid': 18286},
 {'name': 'kworker/5:2', 'pid': 18287},
 {'name': 'kworker/4:0', 'pid': 18315},
 {'name': 'kworker/0:1', 'pid': 18385},
 {'name': 'kworker/6:2', 'pid': 18431},
 {'name': 'kworker/1:2', 'pid': 18489},
 {'name': 'kworker/2:1', 'pid': 18492},
 {'name': 'kworker/7:1', 'pid': 18548},
 {'name': 'chrome', 'pid': 18549},
 {'name': 'kworker/4:3', 'pid': 18567},
 {'name': 'kworker/2:3', 'pid': 18585},
 {'name': 'kworker/0:2', 'pid': 18602},
 {'name': 'chrome', 'pid': 18635},
 {'name': 'kworker/u16:0', 'pid': 18727},
 {'name': 'kworker/3:1', 'pid': 18750},
 {'name': 'bash', 'pid': 18753},
 {'name': 'ZMQbg/1', 'pid': 18777},
 {'name': 'chrome', 'pid': 18847},
 {'name': 'kworker/5:0', 'pid': 18866},
 {'name': 'ZMQbg/1', 'pid': 18877},
 {'name': 'kworker/6:3', 'pid': 18937},
 {'name': 'dconf-service', 'pid': 19622},
 {'name': 'chrome', 'pid': 20180},
 {'name': 'chrome', 'pid': 20396},
 {'name': 'code', 'pid': 20664},
 {'name': 'bash', 'pid': 20690},
 {'name': 'code', 'pid': 20698},
 {'name': 'code', 'pid': 20725},
 {'name': 'code', 'pid': 20981},
 {'name': 'code', 'pid': 20982},
 {'name': 'code', 'pid': 21001},
 {'name': 'chrome', 'pid': 21339},
 {'name': 'chrome', 'pid': 21954},
 {'name': 'chrome', 'pid': 22189},
 {'name': 'chrome', 'pid': 25040},
 {'name': 'chrome', 'pid': 25064},
 {'name': 'chrome', 'pid': 25127},
 {'name': 'chrome', 'pid': 25239},
 {'name': 'chrome', 'pid': 25252},
 {'name': 'chrome', 'pid': 25276},
 {'name': 'chrome', 'pid': 25996},
 {'name': 'chrome', 'pid': 26096},
 {'name': 'chrome', 'pid': 26179},
 {'name': 'chrome', 'pid': 26199},
 {'name': 'chrome', 'pid': 26273},
 {'name': 'chrome', 'pid': 26279},
 {'name': 'chrome', 'pid': 26406},
 {'name': 'chrome', 'pid': 27450},
 {'name': 'chrome', 'pid': 27469},
 {'name': 'chrome', 'pid': 27633},
 {'name': 'chrome', 'pid': 27667},
 {'name': 'chrome', 'pid': 27951},
 {'name': 'chrome', 'pid': 27976},
 {'name': 'chrome', 'pid': 28169},
 {'name': 'chrome', 'pid': 28182}]

In [6]:
myProcess = psutil.Process(os.getpid())